LIBRARY_SHORT_NAME=mylib

SCRIPT_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPT_DIR/..

SOURCE_HEADER=$ROOT_DIR/include/$LIBRARY_NAME/$LIBRARY_NAME.hpp
GENERATED_HEADER=$ROOT_DIR/single_include/$LIBRARY_NAME/$LIBRARY_NAME.hpp

quom $SOURCE_HEADER $GENERATED_HEADER
clang-format -i $GENERATED_HEADER
